apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ray-system

resources:
  - https://github.com/ray-project/kuberay/manifests/cluster-scope-resources/?ref=69ecfceef5c966193ab87f22a9f49250b17e35fb
  - https://github.com/ray-project/kuberay/manifests/overlays/autoscaling/?ref=69ecfceef5c966193ab87f22a9f49250b17e35fb
  - service-nodeports.yaml

images:
  - name: kuberay/operator
    newTag: 69ecfce
  - name: kuberay/apiserver
    newTag: 69ecfce

patches:
  # Permissions in the ClusterRole included in the used ref commit are not enough for the operator to work
  - patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: kuberay-operator
