apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ray-system

resources:
  - https://github.com/ray-project/kuberay/manifests/cluster-scope-resources/?ref=eac60b36fd73b127af0f145ae9aee5c7e4de0e21
  - https://github.com/ray-project/kuberay/manifests/overlays/autoscaling/?ref=eac60b36fd73b127af0f145ae9aee5c7e4de0e21
  - service-nodeports.yaml
  - raycluster-autoscaler.yaml

images:
  - name: kuberay/operator
    newTag: eac60b3
  - name: kuberay/apiserver
    newTag: eac60b3

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --prioritize-workers-to-delete
    target:
      group: apps
      version: v1
      kind: Deployment
      name: kuberay-operator
